#include "cursor_image_mapping.hpp"

// Flutter -> Xcursor
// https://github.com/flutter/engine/blob/2962099077b36704071802ea5595f4a016a1c214/shell/platform/linux/fl_mouse_cursor_plugin.cc#L47
std::map<std::string, const char*> g_cursor_image_mapping = {
	  {"alias",                 "alias"},
	  {"allScroll",             "all-scroll"},
	  {"basic",                 "default"},
	  {"cell",                  "cell"},
	  {"click",                 "pointer"},
	  {"contextMenu",           "context-menu"},
	  {"copy",                  "copy"},
	  {"forbidden",             "not-allowed"},
	  {"grab",                  "grab"},
	  {"grabbing",              "grabbing"},
	  {"help",                  "help"},
	  {"move",                  "move"},
	  {"none",                  "none"},
	  {"noDrop",                "no-drop"},
	  {"precise",               "crosshair"},
	  {"progress",              "progress"},
	  {"text",                  "text"},
	  {"resizeColumn",          "col-resize"},
	  {"resizeDown",            "s-resize"},
	  {"resizeDownLeft",        "sw-resize"},
	  {"resizeDownRight",       "se-resize"},
	  {"resizeLeft",            "w-resize"},
	  {"resizeLeftRight",       "ew-resize"},
	  {"resizeRight",           "e-resize"},
	  {"resizeRow",             "row-resize"},
	  {"resizeUp",              "n-resize"},
	  {"resizeUpDown",          "ns-resize"},
	  {"resizeUpLeft",          "nw-resize"},
	  {"resizeUpRight",         "ne-resize"},
	  {"resizeUpLeftDownRight", "nwse-resize"},
	  {"resizeUpRightDownLeft", "nesw-resize"},
	  {"verticalText",          "vertical-text"},
	  {"wait",                  "wait"},
	  {"zoomIn",                "zoom-in"},
	  {"zoomOut",               "zoom-out"},
};